# Generated by Django 3.2 on 2021-04-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UserName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
