# Generated by Django 3.2 on 2021-04-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0002_alter_userinfo_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='PassWord',
            new_name='PassWord1',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='PassWord2',
            field=models.CharField(default='fakeid1', max_length=50),
            preserve_default=False,
        ),
    ]
