# Generated by Django 3.2 on 2021-04-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0004_auto_20210421_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='PassWord',
            new_name='PassWord1',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='PassWord2',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
